/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as DashboardIndexImport } from './pages/dashboard/index'
import { Route as DashboardStoreIndexImport } from './pages/dashboard/store/index'
import { Route as DashboardMasterUserProductIndexImport } from './pages/dashboard/master-user/product/index'
import { Route as DashboardMasterUserProductCreateImport } from './pages/dashboard/master-user/product/create'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/index.lazy').then((d) => d.Route))

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardStoreIndexRoute = DashboardStoreIndexImport.update({
  id: '/dashboard/store/',
  path: '/dashboard/store/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardMasterUserProductIndexRoute =
  DashboardMasterUserProductIndexImport.update({
    id: '/dashboard/master-user/product/',
    path: '/dashboard/master-user/product/',
    getParentRoute: () => rootRoute,
  } as any)

const DashboardMasterUserProductCreateRoute =
  DashboardMasterUserProductCreateImport.update({
    id: '/dashboard/master-user/product/create',
    path: '/dashboard/master-user/product/create',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/store/': {
      id: '/dashboard/store/'
      path: '/dashboard/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof DashboardStoreIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/master-user/product/create': {
      id: '/dashboard/master-user/product/create'
      path: '/dashboard/master-user/product/create'
      fullPath: '/dashboard/master-user/product/create'
      preLoaderRoute: typeof DashboardMasterUserProductCreateImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/master-user/product/': {
      id: '/dashboard/master-user/product/'
      path: '/dashboard/master-user/product'
      fullPath: '/dashboard/master-user/product'
      preLoaderRoute: typeof DashboardMasterUserProductIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/store': typeof DashboardStoreIndexRoute
  '/dashboard/master-user/product/create': typeof DashboardMasterUserProductCreateRoute
  '/dashboard/master-user/product': typeof DashboardMasterUserProductIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/store': typeof DashboardStoreIndexRoute
  '/dashboard/master-user/product/create': typeof DashboardMasterUserProductCreateRoute
  '/dashboard/master-user/product': typeof DashboardMasterUserProductIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/master-user/product/create': typeof DashboardMasterUserProductCreateRoute
  '/dashboard/master-user/product/': typeof DashboardMasterUserProductIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/store'
    | '/dashboard/master-user/product/create'
    | '/dashboard/master-user/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/store'
    | '/dashboard/master-user/product/create'
    | '/dashboard/master-user/product'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/dashboard/store/'
    | '/dashboard/master-user/product/create'
    | '/dashboard/master-user/product/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStoreIndexRoute: typeof DashboardStoreIndexRoute
  DashboardMasterUserProductCreateRoute: typeof DashboardMasterUserProductCreateRoute
  DashboardMasterUserProductIndexRoute: typeof DashboardMasterUserProductIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStoreIndexRoute: DashboardStoreIndexRoute,
  DashboardMasterUserProductCreateRoute: DashboardMasterUserProductCreateRoute,
  DashboardMasterUserProductIndexRoute: DashboardMasterUserProductIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/",
        "/dashboard/store/",
        "/dashboard/master-user/product/create",
        "/dashboard/master-user/product/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/dashboard/store/": {
      "filePath": "dashboard/store/index.tsx"
    },
    "/dashboard/master-user/product/create": {
      "filePath": "dashboard/master-user/product/create.tsx"
    },
    "/dashboard/master-user/product/": {
      "filePath": "dashboard/master-user/product/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
